import { useEffect, useState } from 'react'
import Head from 'next/head'
import Entry from '../components/Entry'
import Navigation from '../components/Navigation'
import styles from '../styles/Home.module.scss'


export default function Home() {
	const [curEntry, setCurEntry] = useState({})
	const [isLoading, setLoading] = useState(false)

	function handleSelectEntry(e,entry) {
		setCurEntry(entry)
	}

	function handleCreateEntry() {
		//console.log('handleCreateEntry()')
	}

	return (
		<div className={styles.container}>
			<Head>
				<title>nextJS - Diary</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>


			<Entry
				entry={curEntry}
			/>
			
			<Navigation 
				fetchMonth='placeHolder'
				handleSelectEntry={handleSelectEntry}
				handleCreateEntry={handleCreateEntry}
			/>
		</div>
	)
}
